//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGestionCanina_APIandMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacunaciones
    {
        public int IdVacunacion { get; set; }
        public int IdCentro { get; set; }
        public int IdVacuna { get; set; }
        public int IdCanino { get; set; }
        public int IdVacunador { get; set; }
        public int Dosis { get; set; }
        public System.DateTime FechaProxima { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Canino Canino { get; set; }
        public virtual Centros Centros { get; set; }
        public virtual Vacunas Vacunas { get; set; }
        public virtual Vacunadores Vacunadores { get; set; }
    }
}
